centre_equestre/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import monte, cheval, profil, sante
from views import homepage,UserListView

urlpatterns = [
    url(r'^$', homepage),
    url(r'^users/$', UserListView.as_view(), name='users_list'),
    url(r'^monte/', include('monte.urls')),
    url(r'^cheval/', include('cheval.urls')),
    url(r'^profil/', include('profil.urls')),
    url(r'^sante/', include('sante.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monte/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^create/montoir$', CreneauMontoirCreate.as_view(), name='creneau_montoir_create'),
    url(r'^update/montoir/(?P<pk>[\w-]+)$', CreneauMontoirUpdate.as_view(), name='creneau_montoir_update'),
    url(r'^delete/montoir/(?P<pk>[\w-]+)$', CreneauMontoirDelete.as_view(), name='creneau_montoir_delete'),

    url(r'^list/montoir/previsionnel$', CreneauMontoirPrevisionnelList.as_view(), name='creneau_montoir_previsonnel_list'),
    url(r'^list/montoir/reel$', CreneauMontoirReelList.as_view(), name='creneau_montoir_reel_list'),

    url(r'^detail/montoir/previsionnel(?P<pk>[\w-]+)$', CreneauMontoirPrevisionnelDetail.as_view(), name='piquet_montoir_previsionnel'),
    # url(r'^detail/montoir/reel/(?P<pk>[\w-]+)$', CreneauMontoirReelDetail.as_view(), name='piquet_montoir_reel'),

    url(r'^create/montoir/enseignant/(?P<pk_prev>[\w-]+)$', CreneauMontoirReelCreate.as_view(), name='creneau_montoir_enseignant_create'),

    url(r'^list/piquet/reel$', PiquetReelList.as_view(), name='piquet_reel_list'),




    url(r'^piquet/update/(?P<pk>[\w-]+)/json$', PiquetMontoirJsonUpdateView.as_view(), name='update_piquet_json'),




]

sante/urls.py
from django.conf.urls import url
from views import SoinListView, SoinCreateView, SoinUpdateView


urlpatterns = [
    url(r'^$', SoinListView.as_view(), name='soin_list'),
    url(r'^creer/$', SoinCreateView.as_view(), name='soin_create'),
    url(r'^(?P<pk>[\w-]+)/modifier/$', SoinUpdateView.as_view(), name='soin_update'),
]

sante/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

from profil.models import Profil
from cheval.models import Cheval


ACTE_CHOICES = (
    ('1', 'Soin'),
    ('2', 'Vaccin'),
    ('3', 'Ferrage'),
    ('4', 'Vermifugation'),
    ('5', 'Autres'),
)


class Soin(models.Model):
    date        = models.DateField()
    cheval      = models.ForeignKey(Cheval)
    pathologie  = models.CharField(max_length = 100)
    acte        = models.CharField(max_length = 1, choices = ACTE_CHOICES)
    soigneur    = models.ForeignKey(Profil)

    def __unicode__(self):
        return '%s pour %s le %s' % (self.acte, self.cheval, self.date)

sante/forms.py
from django import forms
from models import Soin


class SoinForm(forms.ModelForm):
    class Meta:
        model = Soin
        fields = '__all__'
        widgets = {
            'date':         forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'cheval':       forms.Select(attrs={'class': 'form-control'}),
            'pathologie':   forms.TextInput(attrs={'class': 'form-control'}),
            'acte':         forms.Select(attrs={'class': 'form-control'}),
            'soigneur':     forms.Select(attrs={'class': 'form-control'}),
        }

sante/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.core.urlresolvers import reverse_lazy

from models import Soin
from forms import SoinForm


class SoinListView(ListView):
    model = Soin
    template_name = 'soin.html'
    context_object_name = 'soins'

    def get_context_data(self, **kwargs):
        context = super(SoinListView,self).get_context_data(**kwargs)
        context['form'] = SoinForm()
        return context


class SoinCreateView(CreateView):
    model = Soin
    form_class = SoinForm
    success_url = reverse_lazy('soin_list')


class SoinUpdateView(UpdateView):
    model = Soin
    form_class = SoinForm
    template_name = 'soin_update.html'
    success_url = reverse_lazy('soin_list')

sante/templates/soin.html
{% extends "base.html" %}

{% block title %}Liste des soins effectués{% endblock %}

{% block content %}

<div class="container">
    {% if user.is_authenticated and perms.profil.chef_ecurie %}
    <fieldset>

        <legend class="text-center">Saisie d'un soin</legend>

        <form class="form-inline" action="{% url 'soin_create' %}" method="POST">
            {% csrf_token %}
            {% for field in form %}
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
            {% endfor %}
            <td><button class="btn btn-default" type="submit">Créer</button></td>
        </form>

    </fieldset>
    {% endif %}

    <fieldset>

        <legend class="text-center">Liste des soins effectués</legend>

        <table id="table" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center col-xs-2">Date</th>
                    <th class="text-center col-xs-2">Cheval</th>
                    <th class="text-center col-xs-2">Pathologie</th>
                    <th class="text-center col-xs-2">Acte</th>
                    <th class="text-center col-xs-2">Soigneur</th>
                    {% if user.is_authenticated and perms.profil.chef_ecurie %}
                    <th class="text-center col-xs-2">Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th class="text-center">Date</th>
                    <th class="text-center">Cheval</th>
                    <th class="text-center">Pathologie</th>
                    <th class="text-center">Acte</th>
                    <th class="text-center">Soigneur</th>
                    {% if user.is_authenticated and perms.profil.chef_ecurie %}
                    <th class="text-center">Actions</th>
                    {% endif %}
                </tr>
            </tfoot>
            <tbody>
                {% for soin in soins %}
                <tr>
                    <td>{{ soin.date }}</td>
                    <td>{{ soin.cheval.nom }}</td>
                    <td>{{ soin.pathologie }}</td>
                    <td>{{ soin.get_acte_display }}</td>
                    <td>{{ soin.soigneur }}</td>
                    {% if user.is_authenticated and perms.profil.chef_ecurie %}
                    <td class="text-center">
                        <a href="{% url 'soin_update' soin.pk %}"><i class="fa fa-pencil"></i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </fieldset>
</div>

{% endblock %}

sante/templates/soin_list.html
{% extends "base.html" %}

{% block title %}Liste des soins effectués{% endblock %}

{% block content %}

<div class="container-fluid">
    <fieldset>

        <legend class="text-center">Liste des soins effectués</legend>
        {% if user.is_authenticated and perms.profil.chef_ecurie %}
        <p><a class="btn btn-primary" href="{% url 'soin_create' %}">Nouveau</a></p>
        {% endif %}

        <table id="table" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center col-xs-2">Date</th>
                    <th class="text-center col-xs-2">Cheval</th>
                    <th class="text-center col-xs-2">Pathologie</th>
                    <th class="text-center col-xs-2">Acte</th>
                    <th class="text-center col-xs-2">Soigneur</th>
                    <th class="text-center col-xs-2">Actions</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th class="text-center">Date</th>
                    <th class="text-center">Cheval</th>
                    <th class="text-center">Pathologie</th>
                    <th class="text-center">Acte</th>
                    <th class="text-center">Soigneur</th>
                    <th class="text-center">Actions</th>
                </tr>
            </tfoot>
            <tbody>
                {% for soin in soins %}
                <tr>
                    <td>{{ soin.date }}</td>
                    <td>{{ soin.cheval.nom }}</td>
                    <td>{{ soin.pathologie }}</td>
                    <td>{{ soin.get_acte_display }}</td>
                    <td>{{ soin.soigneur }}</td>
                    <td class="text-center">
                        <a href="{% url 'soin_detail' soin.pk %}"><i class="fa fa-eye"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;
                        {% if user.is_authenticated and perms.profil.chef_ecurie %}
                        <a href="{% url 'soin_update' soin.pk %}"><i class="fa fa-pencil"></i></a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </fieldset>
</div>

{% endblock %}

sante/templates/soin_update.html
{% extends "base.html" %}

{% block title %}Modifier un soin{% endblock %}

{% block content %}

<div class="container">
    <fieldset>

        <legend class="text-center">Modifier un soin</legend>

        <form action="{{ request.path }}" method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            </div>
            {% endfor %}
            <div class="row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    <p><button class="btn btn-success btn-block" type="submit">Enregistrer</button></p>
                    <p><button class="btn btn-default btn-block" type="reset">Annuler les modifications</button></p>
                    <p><a href="{% url 'soin_list' %}"><i class="fa fa-arrow-left"></i> Retour</a></p>
                </div>
            </div>
        </form>

    </fieldset>
</div>

{% endblock %}