centre_equestre/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import monte, cheval, profil, sante
from views import homepage,UserListView

urlpatterns = [
    url(r'^$', homepage),
    url(r'^users/$', UserListView.as_view(), name='users_list'),
    url(r'^monte/', include('monte.urls')),
    url(r'^cheval/', include('cheval.urls')),
    url(r'^profil/', include('profil.urls')),
    url(r'^sante/', include('sante.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monte/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^create/montoir$', CreneauMontoirCreate.as_view(), name='creneau_montoir_create'),
    url(r'^update/montoir/(?P<pk>[\w-]+)$', CreneauMontoirUpdate.as_view(), name='creneau_montoir_update'),
    url(r'^delete/montoir/(?P<pk>[\w-]+)$', CreneauMontoirDelete.as_view(), name='creneau_montoir_delete'),

    url(r'^list/montoir/previsionnel$', CreneauMontoirPrevisionnelList.as_view(), name='creneau_montoir_previsonnel_list'),
    url(r'^list/montoir/reel$', CreneauMontoirReelList.as_view(), name='creneau_montoir_reel_list'),

    url(r'^detail/montoir/previsionnel(?P<pk>[\w-]+)$', CreneauMontoirPrevisionnelDetail.as_view(), name='piquet_montoir_previsionnel'),
    # url(r'^detail/montoir/reel/(?P<pk>[\w-]+)$', CreneauMontoirReelDetail.as_view(), name='piquet_montoir_reel'),

    url(r'^create/montoir/enseignant/(?P<pk_prev>[\w-]+)$', CreneauMontoirReelCreate.as_view(), name='creneau_montoir_enseignant_create'),

    url(r'^list/piquet/reel$', PiquetReelList.as_view(), name='piquet_reel_list'),




    url(r'^piquet/update/(?P<pk>[\w-]+)/json$', PiquetMontoirJsonUpdateView.as_view(), name='update_piquet_json'),




]

profil/urls.py
from django.conf.urls import url
from views import CreateProfil, ListProfil, ProfilDetail, ProfilUpdate, CreatePublic, ListPublic, PublicUpdate


urlpatterns = [
    url(r'^$', ListProfil.as_view(), name='list_profil'),
    url(r'^create$', CreateProfil.as_view(), name='create_profil'),
    url(r'^detail/(?P<pk>[\w-]+)$', ProfilDetail.as_view(), name='detail_profil'),
    url(r'^(?P<pk>[\w-]+)$', ProfilUpdate.as_view(), name='profil_update'),
    url(r'^public/edit$', CreatePublic.as_view(), name='create_public'),
    url(r'^public/list$', ListPublic.as_view(), name='list_public'),
    url(r'^public/(?P<pk>[\w-]+)$', PublicUpdate.as_view(), name='public_update'),
    # url(r'^vue_profil/(?P<id>[\w-]+)$', edit_profil),
]

profil/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver





categorie_choices = (
    ('1','Elève'),
    ('2','Cavalier'),
    ('3','Professeur'),
    ('4','Personnel'),
    ('5','Autre'), #veto ?
    )

civilite_choices = (
    ('1','Mr'),
    ('2','Mme'),
    ('3','Mlle'),
    )

perms_choices = (
    ('1','Professeur'),
    ('2',"Chef d'écurie"),
    )

class Profil(models.Model):
    user         = models.OneToOneField(User, null=True, related_name="profile" )
    civilite     = models.CharField(max_length=3, choices = civilite_choices)
    nom          = models.CharField(max_length=200)
    prenom       = models.CharField(max_length=200)
    email        = models.CharField(max_length=200)
    adresse      = models.CharField(max_length=200)
    cp           = models.CharField(max_length=5)
    ville        = models.CharField(max_length=100)
    tel_1        = models.CharField(max_length=10)
    tel_2        = models.CharField(max_length=10)
    tel_3        = models.CharField(max_length=10)
    profil_actif = models.BooleanField(default=False)
    permis       = models.CharField(max_length=30, choices=perms_choices, null=True, blank=True)

    class Meta:
        permissions = (
        ("chef_ecurie", "Look all and modif Chevaux and Monte"),
        ("professeur", "Look all and modif Piquet cours"),
        )

    def __unicode__(self):
        return "%s %s" % (self.nom, self.prenom)


class Public(models.Model):
    nom = models.CharField(max_length=30)

    def __unicode__(self):
        return "%s" % (self.nom)


class Periode(models.Model):
    categorie  = models.CharField(max_length=100, choices=categorie_choices)
    public     = models.ForeignKey(Public, null=True, blank=True)
    license    = models.CharField(max_length = 60, null=True, blank=True)
    debut      = models.DateField()
    fin        = models.DateField(null=True, blank=True)
    profil     = models.ForeignKey(Profil)

    def __unicode__(self):
        return "%s %s %s" % (self.debut, self.fin, self.license)



@receiver(post_save, sender=Profil)

def active_user(sender, instance, created, **kwargs):
    if created:
        user = User(email=instance.email,
                                   first_name=instance.prenom,
                                   last_name=instance.nom,
                                   username=instance.nom,
                                   is_active=instance.profil_actif)
        user.set_password("plop48000")
        user.save()
        instance.user = user
        instance.save()

profil/forms.py
from django.forms import ModelForm, modelform_factory
from django.forms.models import inlineformset_factory
from models import Profil, Periode

ProfilLineFormSet = inlineformset_factory(Profil, Periode,
                                            fields='__all__',
                                            extra=1)

profil/views.py
from django.shortcuts import render, redirect
from models import Profil, Public, Periode
from django.contrib.auth.models import User, Group
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.core.urlresolvers import reverse_lazy, reverse
from .forms import ProfilLineFormSet
# from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin



class CreateProfil(CreateView):
    model = Profil
    fields = ['civilite', 'nom', 'prenom', 'email', 'adresse', 'cp', 'ville', 'tel_1', 'tel_2', 'tel_3', 'profil_actif', 'permis']
    template_name = 'create_profil.html'
    success_url = reverse_lazy('list_profil')

    def get_context_data(self, **kwargs):
        context = super(CreateProfil, self).get_context_data(**kwargs)
        context ["profilline_formset"] = ProfilLineFormSet()
        return context

    def form_valid(self, form):
        profilline_formset = ProfilLineFormSet(self.request.POST)
        if form.is_valid() and profilline_formset.is_valid():
            profil = form.save()
            profilline_formset = ProfilLineFormSet(self.request.POST, instance=profil)
            profilline_formset.is_valid()
            profilline_formset.save()
            chef_ecurie = Group.objects.get(name='Chef_ecurie')
            professeur  = Group.objects.get(name='Professeur')
            user        = User.objects.get(username=profil.user.username)
            if profil.permis == "1":
                user.groups.add(professeur)
            if profil.permis == "2":
                user.groups.add(chef_ecurie)
            return redirect(reverse('list_profil'))
        return self.render_to_response(self.get_context_data(form=form))



class ListProfil(ListView):
    model = Profil
    template_name = "list_profil.html"
    context_object_name = "profils"
    queryset = Profil.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ListProfil, self).get_context_data(**kwargs)
        context['periodes'] = Periode.objects.all()
        return context


class ProfilDetail(DetailView):
    model = Profil
    template_name = 'display_profil.html'
    context_object_name = 'profil'


class ProfilUpdate(UpdateView):
    model = Profil
    fields = ['civilite', 'nom', 'prenom', 'email', 'adresse', 'cp', 'ville', 'tel_1', 'tel_2', 'tel_3', 'profil_actif', 'permis']
    template_name = 'profil_update.html'
    success_url = reverse_lazy('list_profil')

    def get_context_data(self, **kwargs):
        context = super(ProfilUpdate, self).get_context_data(**kwargs)
        context ["periodes"] = ProfilLineFormSet(instance=self.get_object())
        return context

    def form_valid(self, form):
        profilline_formset = ProfilLineFormSet(self.request.POST, instance=self.get_object())
        if form.is_valid() and profilline_formset.is_valid():
            profil = form.save()
            #(Des)Activation du User
            profil.user.is_active = profil.profil_actif
            profil.user.save()
            profilline_formset.save()
            chef_ecurie = Group.objects.get(name='Chef_ecurie')
            professeur  = Group.objects.get(name='Professeur')
            user        = User.objects.get(username=profil.user.username)
            user_group  = user.groups.all()
            if profil.permis == "1":
                user.groups.clear()
                user.groups.add(professeur)
            elif profil.permis == "2":
                user.groups.clear()
                user.groups.add(chef_ecurie)
            else:
                user.groups.clear()
            return redirect(reverse('list_profil'))
        return self.render_to_response(self.get_context_data(form=form))

# =====================================================


class CreatePublic(CreateView):
    model = Public
    fields = '__all__'
    template_name = 'create_public.html'
    success_url = reverse_lazy('list_public')


class ListPublic(ListView):
    model = Public
    template_name = "list_public.html"
    context_object_name = "publics"
    queryset = Public.objects.all()


class PublicUpdate(UpdateView):
    model = Public
    fields = '__all__'
    template_name = 'public_update.html'
    success_url = reverse_lazy('list_public')

profil/templates/create_profil.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Enregistrement d'un nouveau Profil{% endblock %}
{% block content %}

<!-- <div class="container">
    <fieldset>
        <legend class="text-center">Fiche Création de Profil</legend>

        <p><a href="{% url 'list_profil' %}"><i class="fa fa-arrow-left"></i> Retour</a></p>
        <form action="{{ request.path }}" method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row">
                <div class="col-sm-1 col-sm-offset-2">
                    {{ field.label_tag }}
                </div>
                <div class="col-sm-7">
                    {{ field }}
                    {{ field.errors }}
                </div>
            </div>
            {% endfor %}
            <hr>
            {{profilline_formset.management_form}}
            {% for field in profilline_formset %}
            <div class="profil_line">
                <div class="form-group row perm categorie">
                    <div class="col-sm-1 col-sm-offset-2">
                        {{ field.categorie.label_tag }}
                    </div>
                    <div class="col-sm-7">
                        {{ field.categorie.errors }}
                        {{ field.categorie }}
                    </div>
                </div>
                <div class="form-group row perm public">
                    <div class="col-sm-1 col-sm-offset-2">
                        {{ field.public.label_tag }}
                    </div>
                    <div class="col-sm-7">
                        {{ field.public.errors }}
                        {{ field.public }}
                    </div>
                </div>
                <div class="form-group row perm license">
                    <div class="col-sm-1 col-sm-offset-2">
                        {{ field.license.label_tag }}
                    </div>
                    <div class="col-sm-7">
                        {{ field.license.errors }}
                        {{ field.license }}
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-1 col-sm-offset-2">
                        {{ field.debut.label_tag }}
                    </div>
                    <div class="col-sm-7 debut">
                        {{ field.debut.errors }}
                        {{ field.debut }}
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-1 col-sm-offset-2">
                        {{ field.fin.label_tag }}
                    </div>
                    <div class="col-sm-7 fin">
                        {{ field.fin.errors }}
                        {{ field.fin }}
                    </div>
                </div>
            </div>
                {% endfor %}
            <div class="row">
                <div class="col-sm-1 col-sm-offset-5">
                    <p><button class="btn btn-success" type="submit">Enregistrer</button></p>
                </div>
            </div>
        </form>

    </fieldset>
</div> -->

<div class="container-fluid">
    <fieldset>
        <legend class="text-center">Enregistrement d'un nouveau Profil</legend>
        <form action="{{ request.path }}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            </div>
            {% endfor %}
            <hr>
            {{profilline_formset.management_form}}
            {% for field in profilline_formset %}
            <div class="profil_line">
                <div class="form-group row perm categorie">
                    <div class="col-xs-12 col-md-4 col-md-offset-4">
                        {{ field.categorie.label_tag }}
                        {{ field.categorie.errors }}
                        {{ field.categorie }}
                    </div>
                </div>
                <div class="form-group row perm public">
                    <div class="col-xs-12 col-md-4 col-md-offset-4">
                        {{ field.public.label_tag }}
                        {{ field.public.errors }}
                        {{ field.public }}
                    </div>
                </div>
                <div class="form-group row perm license">
                    <div class="col-xs-12 col-md-4 col-md-offset-4">
                        {{ field.license.label_tag }}
                        {{ field.license.errors }}
                        {{ field.license }}
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-xs-12 col-md-4 col-md-offset-4">
                        {{ field.debut.label_tag }}
                        {{ field.debut.errors }}
                        {{ field.debut }}
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-xs-12 col-md-4 col-md-offset-4">
                        {{ field.fin.label_tag }}
                        {{ field.fin.errors }}
                        {{ field.fin }}
                    </div>
                </div>
            </div>
                {% endfor %}
            <div class="row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    <p><button class="btn btn-success btn-block" type="submit">Enregistrer</button></p>
                    <p><button class="btn btn-default btn-block" type="reset">Vider les champs</button></p>
                    <p class="text-center"><a type="button" class="btn btn-primary"href="{% url 'list_profil' %}"><i class="fa fa-arrow-left"></i> Retour</a></p>
                </div>
            </div>
        </form>

    </fieldset>
</div>

<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
    var debut = $("input[id$='debut']");
    var fin = $("input[id$='fin']");
    $(debut).datepicker({
        format: 'dd/mm/yyyy',
        weekStart: 1
    });
    $(fin).datepicker({
        format: 'dd/mm/yyyy',
        weekStart: 1
    });

    var permis    = $('#id_permis');
    var perms     = $('.perm');
    var actif     = $('#id_profil_actif');
    var categorie = $("[id$='categorie']");
    var license   = $("[id$='license']");
    var publi     = $("[id$='public']");

    license.parent().parent().hide();
    permis.parent().parent().hide();

    if (actif.is(":checked")) {
        permis.parent().parent().show();
    }
    actif.change(function() {
        if (this.checked){
            permis.parent().parent().show();
            $('#id_permis').val(1);
            categorie.val(3);
            perms.hide();
         }else{
            permis.parent().parent().hide();
            $('#id_permis').val(0);
            categorie.val(0);
            perms.show();
            license.parent().parent().hide();
         }
    });

    permis.change(function() {
        var perm = $('#id_permis option:selected').text();
        if (perm === "Professeur") {
            categorie.val(3);
        }else if(perm === "Chef d'écurie"){
            categorie.val(4);
        }else{
            categorie.val(0);
        }
    });

    categorie.change(function() {
        var cat = $("[id$='categorie'] option:selected").text();
        if (cat === "Cavalier") {
            publi.val(2);
            license.parent().parent().show();
        }else if(cat === "Elève"){
            publi.val(1);
            license.parent().parent().hide();
        }else{
            publi.val(0);
            license.parent().parent().hide();
        }
    });

    publi.change(function() {
        var pub = $("[id$='public'] option:selected").text();
        if (pub === "Club") {
            license.parent().parent().show();
        }else{
            license.parent().parent().hide();
        }
    });

    $(function reloadForm() {
        $('input').addClass('form-control');
        $('select').addClass('form-control');
        $('#id_profil_actif').removeClass('form-control');
        $('#id_profil_actif').addClass('checkbox');
    })
    $(function() {
        $('.profil_line').formset({
            deleteText: '<i class="fa fa-trash"></i>',
            addText: '<i class="fa fa-plus"></i>',
            prefix: '{{ profilline_formset.prefix }}',
        });reloadForm()

    })
</script>

{% endblock %}

profil/templates/create_public.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <fieldset>
            <legend>Fiche Public</legend>
           <form class="" action="{{ request.path }}" method="post">
                {% csrf_token %}
                {% for field in form%}
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2">
                            {{field.label_tag}}
                        </div>
                        <div class="col-md-10">
                            {{field}}
                            {{field.errors}}
                            {% if field.help_text %}
                            {{field.help_text}}
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
                <div id="btn-profil">
                    <input id="btn-valid-profil" type="submit" name="name" value="Envoyer">
                </div>
            </form>
        </fieldset>
    </div>
</div>

{% endblock %}

profil/templates/display_profil.html
{% extends "base.html" %}
{% load phonenumber_filters %}

{% block content %}
<div class="container">
    <fieldset>
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
                <table class="table">
                    <caption class="text-center"><h1>Profil de {{ profil.get_civilite_display }} {{ profil.nom }} {{ profil.prenom }}</h1></caption>
                    <tr>
                        <td style="width:50%"><a type="button" class="btn btn-primary pull-left"href="{% url 'list_profil' %}"><i class="fa fa-arrow-left"></i> Retour</a></td>
                        {% if user.is_authenticated and perms.profil.chef_ecurie %}
                        <td class=""><a type="button" class="btn btn-primary pull-right"href="{% url 'profil_update' profil.id %}"><i class="fa fa-pencil-square-o fa-2x"></i></a></td>
                        {% endif %}
                    </tr>
                </table>

                <table class="table table-striped table-hover table-bordered">
                    {% if profil.nom %}
                    <tr>
                        <td style="width:50%; font-weight:bold">Nom:</td>
                        <td class="">{{profil.nom}}</td>
                    </tr>
                    {% endif %}
                    {% if profil.prenom %}
                    <tr>
                        <td style="width:50%; font-weight:bold">Prénom:</td>
                        <td class="">{{profil.prenom}}</td>
                    </tr>
                    {% endif %}
                    {% if profil.email %}
                    <tr>
                        <td style="width:50%; font-weight:bold">Email:</td>
                        <td class=""><a href="mailto:{{profil.email}}">{{profil.email}}</a></td>
                    </tr>
                    {% endif %}
                    {% if profil.adresse %}
                    <tr>
                        <td style="width:50%; font-weight:bold">Adresse:</td>
                        <td class="">{{profil.adresse}}, {{profil.cp}} {{profil.ville}}</td>
                    </tr>
                    {% endif %}
                    {% if profil.tel_1 %}
                    <tr>
                        <td style="width:50%; font-weight:bold">Tel 1:</td>
                        <td class="">{{profil.tel_1|phonenumber:"FR"}}</td>
                    </tr>
                    {% endif %}
                    {% if profil.tel_2 %}
                    <tr>
                        <td style="width:50%; font-weight:bold">Tel 2:</td>
                        <td class="">{{profil.tel_2|phonenumber:"FR"}}</td>
                    </tr>
                    {% endif %}
                    {% if profil.tel_3 %}
                    <tr>
                        <td style="width:50%; font-weight:bold">Tel 3:</td>
                        <td class="">{{profil.tel_3|phonenumber:"FR"}}</td>
                    </tr>
                    {% endif %}


                    <tr>
                        <td style="width:50%; font-weight:bold">Catégorie:</td>
                        <td class="">
                        {% for periode in profil.periode_set.all %}
                                {{periode.get_categorie_display}}{% if not forloop.last%},{%endif%}
                        {% endfor %}
                        </td>
                    </tr>
                    {% for periode in profil.periode_set.all %}
                    {% if periode.public %}
                    <tr>
                        <td style="width:50%; font-weight:bold">Classe:</td>
                        <td class="">
                                {{periode.public.nom}}{% if not forloop.last%},{%endif%}
                        </td>
                    </tr>
                    {% endif %}
                    {% endfor %}

                    {% for periode in profil.periode_set.all %}
                        {% if periode.license %}
                            <tr>
                                <td style="width:50%; font-weight:bold">License:</td>
                                <td class="">
                                    {{periode.license}}
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}

                    {% for periode in profil.periode_set.all %}
                        <tr>
                            {% if forloop.first%}
                            <td style="width:50%; font-weight:bold" rowspan="{{profil.periode_set.count}}">Date d'entrée:</td>
                            {% endif %}
                            <td class="date-profil">
                                    {{periode.get_categorie_display}} : {{periode.debut|date:"d M Y"}}
                            </td>
                        </tr>
                    {% endfor %}

                    {% for periode in profil.periode_set.all %}
                    {% if periode.fin %}
                        <tr>
                            {% if forloop.first%}
                            <td style="width:50%; font-weight:bold" rowspan="{{profil.periode_set.count}}">Date de sortie:</td>
                            {% endif %}
                            <td class="">
                                {{periode.get_categorie_display}} : {{periode.fin|date:"d M Y"}}
                            </td>
                        </tr>
                    {% endif %}
                    {% endfor %}
                </table>
            </div>
        </div>
    </fieldset>
</div>
{% endblock %}

profil/templates/profil_update.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="container">
    <fieldset>
        <legend class="text-center">Fiche de {{profil.get_civilite_display}} {{profil.nom}} {{profil.prenom}}</legend>
        <form action="{{ request.path }}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            </div>
            {% endfor %}
            <hr>
            {{periodes.management_form}}
            <div class="row">
            {% for field in periodes %}
                <div class="col-sm-4 col-sm-offset-0">
                    <div class="form-group">
                        <div class="blank">
                            {{ field.id.label_tag }}
                            {{ field.id.errors }}
                            {{ field.id }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div>
                            {{ field.categorie.label_tag }}
                            {{ field.categorie.errors }}
                            {{ field.categorie }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div>
                            {{ field.public.label_tag }}
                            {{ field.public.errors }}
                            {{ field.public }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div>
                            {{ field.license.label_tag }}
                            {{ field.license.errors }}
                            {{ field.license }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div>
                            {{ field.debut.label_tag }}
                            {{ field.debut.errors }}
                            {{ field.debut }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div>
                            {{ field.fin.label_tag }}
                            {{ field.fin.errors }}
                            {{ field.fin }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
            <div class="row btnup">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    <p><button class="btn btn-success btn-block" type="submit">Enregistrer</button></p>
                    <p class="text-center"><a type="button" class="btn btn-primary"href="{% url 'list_profil' %}"><i class="fa fa-arrow-left"></i> Retour</a></p>
                </div>
            </div>
        </form>
    </fieldset>
</div>
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
    var debut = $("input[id$='debut']");
    var fin = $("input[id$='fin']");
    $(debut).datepicker({
        format: 'dd/mm/yyyy',
        weekStart: 1
    });
    $(fin).datepicker({
        format: 'dd/mm/yyyy',
        weekStart: 1
    });

    // var permis    = $('#id_permis');
    // var perms     = $('.perm');
    // var actif     = $('#id_profil_actif');
    // var categorie = $("[id$='0-categorie']");
    // var license   = $("[id$='license']");
    // var publi     = $("[id$='public']");
    //
    // license.parent().parent().hide();
    // permis.parent().parent().hide();
    //
    // if (actif.is(":checked")) {
    //     permis.parent().parent().show();
    // }
    // actif.change(function() {
    // if (this.checked){
    //     permis.parent().parent().show();
    //     $('#id_permis').val(1);
    //     categorie.val(3);
    //     // perms.hide();
    // }else{
    //     permis.parent().parent().hide();
    //     $('#id_permis').val(0);
    //     categorie.val(0);
    //     perms.show();
    //     license.parent().parent().hide();
    // }
    // });
    //
    // permis.change(function() {
    //     var perm = $('#id_permis option:selected').text();
    //     if (perm === "Professeur") {
    //         categorie.val(3);
    //     }else if(perm === "Chef d'écurie"){
    //         categorie.val(4);
    //     }else{
    //         categorie.val(0);
    //     }
    // });
    //
    // categorie.change(function() {
    //     var cat = $("[id$='categorie'] option:selected").text();
    //     if (cat === "Cavalier") {
    //         publi.val(2);
    //         license.parent().parent().show();
    //     }else if(cat === "Elève"){
    //         publi.val(1);
    //         license.parent().parent().hide();
    //     }else{
    //         publi.val(0);
    //         license.parent().parent().hide();
    //     }
    // });
    //
    // publi.change(function() {
    //     var pub = $("[id$='public'] option:selected").text();
    //     if (pub === "Club") {
    //         license.parent().parent().show();
    //     }else{
    //         license.parent().parent().hide();
    //     }
    // });

    $(function reloadForm() {
        $('input').addClass('form-control');
        $('select').addClass('form-control');
        $('#id_profil_actif').removeClass('form-control');
        $('#id_profil_actif').addClass('checkbox');
    })
    // $(function() {
    //     $('.profil_line').formset({
    //         deleteText: '<i class="fa fa-trash"></i>',
    //         addText: '<i class="fa fa-plus"></i>',
    //         prefix: '{{ profilline_formset.prefix }}',
    //     });reloadForm()
    // });
</script>
{% endblock %}