centre_equestre/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import monte, cheval, profil, sante
from views import homepage,UserListView

urlpatterns = [
    url(r'^$', homepage),
    url(r'^users/$', UserListView.as_view(), name='users_list'),
    url(r'^monte/', include('monte.urls')),
    url(r'^cheval/', include('cheval.urls')),
    url(r'^profil/', include('profil.urls')),
    url(r'^sante/', include('sante.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cheval/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from views import ChevalListView, ChevalCreateView, ChevalDetailView, ChevalUpdateView, ChevalEtatView, AptitudeUpdateView, JournalListView, JournalCreateView, JournalUpdateView, EmplacementListView, EmplacementCreateView, EmplacementUpdateView, EmplacementDeleteView


urlpatterns = [

    url(r'^$', ChevalListView.as_view(), name='cheval_list'),
    url(r'^creer/$', ChevalCreateView.as_view(), name='cheval_create'),
    url(r'^(?P<pk>[\w-]+)$', ChevalDetailView.as_view(), name='cheval_detail'),
    url(r'^(?P<pk>[\w-]+)/modifier/$', ChevalUpdateView.as_view(), name='cheval_update'),


    url(r'^etat/$', ChevalEtatView.as_view(), name='cheval_etat'),
    url(r'^etat/(?P<pk>[\w-]+)/update$', AptitudeUpdateView.as_view(), name='aptitude_update'),


    url(r'^journal/$', JournalListView.as_view(), name='journal_list'),
    url(r'^journal/creer/$', JournalCreateView.as_view(), name='journal_create'),
    url(r'^journal/(?P<pk>[\w-]+)/modifier/$', JournalUpdateView.as_view(), name='journal_update'),


    url(r'^emplacement/$', EmplacementListView.as_view(), name='emplacement_list'),
    url(r'^emplacement/creer/$', EmplacementCreateView.as_view(), name='emplacement_create'),
    url(r'^emplacement/(?P<pk>[\w-]+)/modifier/$', EmplacementUpdateView.as_view(), name='emplacement_update'),
    url(r'^emplacement/(?P<pk>[\w-]+)/supprimer/$', EmplacementDeleteView.as_view(), name='emplacement_delete'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monte/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^create/montoir$', CreneauMontoirCreate.as_view(), name='creneau_montoir_create'),
    url(r'^update/montoir/(?P<pk>[\w-]+)$', CreneauMontoirUpdate.as_view(), name='creneau_montoir_update'),
    url(r'^delete/montoir/(?P<pk>[\w-]+)$', CreneauMontoirDelete.as_view(), name='creneau_montoir_delete'),

    url(r'^list/montoir/previsionnel$', CreneauMontoirPrevisionnelList.as_view(), name='creneau_montoir_previsonnel_list'),
    url(r'^list/montoir/reel$', CreneauMontoirReelList.as_view(), name='creneau_montoir_reel_list'),

    url(r'^detail/montoir/previsionnel(?P<pk>[\w-]+)$', CreneauMontoirPrevisionnelDetail.as_view(), name='piquet_montoir_previsionnel'),
    # url(r'^detail/montoir/reel/(?P<pk>[\w-]+)$', CreneauMontoirReelDetail.as_view(), name='piquet_montoir_reel'),

    url(r'^create/montoir/enseignant/(?P<pk_prev>[\w-]+)$', CreneauMontoirReelCreate.as_view(), name='creneau_montoir_enseignant_create'),

    url(r'^list/piquet/reel$', PiquetReelList.as_view(), name='piquet_reel_list'),




    url(r'^piquet/update/(?P<pk>[\w-]+)/json$', PiquetMontoirJsonUpdateView.as_view(), name='update_piquet_json'),




]

cheval/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import date


STATUT_CHOICES = (
    ('1', 'Propriété'),
    ('2', 'Commodat'),
    ('3', 'Pension'),
    ('4', 'Débourrage'),
    ('5', 'Autres'),
)

ACTIVITE_CHOICES = (
    ('1', 'Monte'),
    ('2', 'Élevage'),
)

APTITUDE_CHOICES = (
    ('1', 'Apte'),
    ('2', 'Repos'),
    ('3', 'Infirmerie'),
    ('4', 'Autres'),
)


class Emplacement(models.Model):
    zone    = models.CharField(max_length = 100)
    box     = models.CharField(max_length = 100, unique = True, null = True)

    def __unicode__(self):
        return 'Zone %s - box %s' % (self.zone, self.box)

    def serialize(self):
        return {
            'zone': self.zone,
            'box': self.box,
        }


class Cheval(models.Model):
    sire            = models.IntegerField(unique = True)
    nom             = models.CharField(max_length = 100)
    race            = models.CharField(max_length = 100)
    pedigree        = models.CharField(max_length = 100)
    annee_naissance = models.IntegerField()
    photo           = models.FileField(upload_to = 'photos')
    date_entree     = models.DateField(auto_now_add = True)
    date_sortie     = models.DateField(null = True, blank = True)
    activite        = models.CharField(max_length = 1, choices = ACTIVITE_CHOICES)
    remarques       = models.TextField()
    statut          = models.CharField(max_length = 1, choices = STATUT_CHOICES)
    aptitude        = models.CharField(max_length = 1, choices = APTITUDE_CHOICES, default = '1')
    emplacement     = models.OneToOneField(Emplacement, unique = True)

    class Meta:
        verbose_name_plural = 'Chevaux'

    def get_dernier_soin(self):
        return self.soin_set.filter(acte = 1).order_by('-date').first()

    def get_dernier_vaccin(self):
        return self.soin_set.filter(acte = 2).order_by('-date').first()

    def get_dernier_ferrage(self):
        return self.soin_set.filter(acte = 3).order_by('-date').first()

    def get_derniere_vermifugation(self):
        return self.soin_set.filter(acte = 4).order_by('-date').first()

    def __unicode__(self):
        return self.nom

    def serialize(self):
        return {
            'sire': self.sire,
            'nom': self.nom,
            'race': self.race,
            'pedigree': self.pedigree,
            'annee_naissance': self.annee_naissance,
            'date_entree': self.date_entree,
            'date_sortie': self.date_sortie,
            'activite': self.activite,
            'remarques': self.remarques,
            'statut': self.statut,
            'aptitude': self.aptitude,
            'emplacement': self.emplacement,
        }


@receiver(post_save, sender = Cheval)
def add_cheval_piquet_montoir_staff(sender, instance, created, **kwargs):
    from monte.models import CreneauMontoir, PiquetMontoirStaff
    if not PiquetMontoirStaff.objects.filter(cheval = instance):
        if instance.activite == '1' and (created or (created == False and (not instance.date_sortie or instance.date_sortie > date.today()))):
            for montoir in CreneauMontoir.objects.all():
                PiquetMontoirStaff.objects.create(montoir = montoir, cheval = instance)


@receiver(post_save, sender = Cheval)
def del_cheval_piquet_montoir_staff(sender, instance, created, **kwargs):
    from monte.models import CreneauMontoir, PiquetMontoirStaff
    if created == False and (instance.date_sortie and instance.date_sortie <= date.today()) or instance.activite == '2':
        for montoir in CreneauMontoir.objects.all():
            PiquetMontoirStaff.objects.filter(cheval = instance).delete()


class Journal(models.Model):
    cheval  = models.ForeignKey(Cheval)
    date    = models.DateField()
    motif   = models.CharField(max_length = 100)
    lieu    = models.CharField(max_length = 100)

    class Meta:
        verbose_name_plural = 'Journaux'

    def __unicode__(self):
        return '%s %s' % (self.cheval.nom, self.lieu)

cheval/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import Cheval, Journal, Emplacement


class ChevalForm(forms.ModelForm):
    class Meta:
        model = Cheval
        fields = ['sire', 'nom', 'race', 'pedigree', 'annee_naissance', 'photo', 'activite', 'remarques', 'statut', 'aptitude', 'emplacement']
        labels = {
            'sire':             'Numéro SIRE',
            'annee_naissance':  'Année de naissance',
            'activite':         'Activité pratiquée',
        }
        widgets = {
            'sire':             forms.TextInput(attrs={'class': 'form-control'}),
            'nom':              forms.TextInput(attrs={'class': 'form-control'}),
            'race':             forms.TextInput(attrs={'class': 'form-control'}),
            'pedigree':         forms.TextInput(attrs={'class': 'form-control'}),
            'annee_naissance':  forms.TextInput(attrs={'class': 'form-control'}),
            'activite':         forms.Select(attrs={'class': 'form-control'}),
            'remarques':        forms.TextInput(attrs={'class': 'form-control'}),
            'statut':           forms.Select(attrs={'class': 'form-control'}),
            'aptitude':         forms.Select(attrs={'class': 'form-control'}),
            'emplacement':      forms.Select(attrs={'class': 'form-control'}),
        }


class AptitudeForm(forms.ModelForm):
    class Meta:
        model = Cheval
        fields = ['aptitude']
        widgets = {
            'aptitude': forms.Select(attrs={'class': 'form-control'}),
        }


class JournalForm(forms.ModelForm):
    class Meta:
        model = Journal
        fields = '__all__'
        widgets = {
            'cheval':   forms.Select(attrs={'class': 'form-control'}),
            'date':     forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'motif':    forms.TextInput(attrs={'class': 'form-control'}),
            'lieu':     forms.TextInput(attrs={'class': 'form-control'}),
        }


class EmplacementForm(forms.ModelForm):
    class Meta:
        model = Emplacement
        fields = '__all__'
        widgets = {
            'zone': forms.TextInput(attrs={'class': 'form-control'}),
            'box':  forms.TextInput(attrs={'class': 'form-control'}),
        }

cheval/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from models import Cheval, Journal, Emplacement
from forms import ChevalForm, AptitudeForm, JournalForm, EmplacementForm


class ChevalListView(ListView):
    model = Cheval
    template_name = 'cheval_list.html'
    context_object_name = 'chevaux'


class ChevalCreateView(CreateView):
    model = Cheval
    form_class = ChevalForm
    template_name = 'cheval_create.html'
    success_url = reverse_lazy('cheval_list')


class ChevalDetailView(DetailView):
    model = Cheval
    template_name = 'cheval_detail.html'
    context_object_name = 'cheval'


class ChevalUpdateView(UpdateView):
    model = Cheval
    form_class = ChevalForm
    template_name = 'cheval_update.html'
    success_url = reverse_lazy('cheval_list')


class ChevalEtatView(ListView):
    model = Cheval
    template_name = 'cheval_etat.html'
    context_object_name = 'chevaux'

    def get_context_data(self, **kwargs):
        context = super(ChevalEtatView, self).get_context_data(**kwargs)
        chevaux = {}
        for cheval in self.get_queryset():
            chevaux[cheval] = AptitudeForm(instance = cheval)
        context['chevaux'] = chevaux
        context['form'] = AptitudeForm()
        return context


class AptitudeUpdateView(UpdateView):
    model = Cheval
    form_class = AptitudeForm
    success_url = reverse_lazy('cheval_etat')


class EmplacementListView(ListView):
    model = Emplacement
    template_name = 'emplacement.html'
    context_object_name = 'emplacements'

    def get_context_data(self, **kwargs):
        context = super(EmplacementListView,self).get_context_data(**kwargs)
        context['form'] = EmplacementForm()
        return context


class EmplacementCreateView(CreateView):
    model = Emplacement
    form_class = EmplacementForm
    success_url = reverse_lazy('emplacement_list')


class EmplacementUpdateView(UpdateView):
    model = Emplacement
    form_class = EmplacementForm
    template_name = 'emplacement_update.html'
    success_url = reverse_lazy('emplacement_list')


class EmplacementDeleteView(DeleteView):
    model = Emplacement
    template_name = 'emplacement_delete.html'
    success_url = reverse_lazy('emplacement_list')


class JournalListView(ListView):
    model = Journal
    template_name = 'journal.html'
    context_object_name = 'journaux'

    def get_context_data(self, **kwargs):
        context = super(JournalListView,self).get_context_data(**kwargs)
        context['form'] = JournalForm()
        return context


class JournalCreateView(CreateView):
    model = Journal
    form_class = JournalForm
    success_url = reverse_lazy('journal_list')


class JournalUpdateView(UpdateView):
    model = Journal
    form_class = JournalForm
    template_name = 'journal_update.html'
    success_url = reverse_lazy('journal_list')

cheval/templates/cheval_create.html
{% extends "base.html" %}

{% block title %}Enregistrer un nouveau cheval{% endblock %}

{% block content %}

<div class="container">
    <fieldset>

        <legend class="text-center">Enregistrer un nouveau cheval</legend>

        <form action="{% url 'cheval_create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            </div>
            {% endfor %}
            <div class="row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    <p><button class="btn btn-success btn-block" type="submit">Enregistrer</button></p>
                    <p><button class="btn btn-default btn-block" type="reset">Vider les champs</button></p>
                    <p><a href="{% url 'cheval_list' %}"><i class="fa fa-arrow-left"></i> Retour</a></p>
                </div>
            </div>
        </form>

    </fieldset>
</div>

{% endblock %}

cheval/templates/cheval_detail.html
{% extends "base.html" %}

{% block title %}Fiche de {{ cheval.nom }}{% endblock %}

{% block content %}

<div class="container">
    <fieldset>

        <legend class="text-center">Fiche de {{ cheval.nom }}</legend>

        <div class="row">
            <div class="col-xs-12 col-md-6 col-md-push-6">
                <img alt="Photo du cheval" src="/media/{{cheval.photo}}" class="img-responsive" />
            </div>
            <div class="col-xs-12 col-md-6 col-md-pull-6">
                <p>Nom : {{ cheval.nom }}</p>
                <p>Numéro SIRE : {{ cheval.sire }}</p>
                <p>Race : {{ cheval.race }}</p>
                <p>Pedigree : {{ cheval.pedigree }}</p>
                <p>Année de naissance : {{ cheval.annee_naissance }}</p>
                <p>Date d'entrée : {{ cheval.date_entree }}</p>
                <p>Date de sortie : {{ cheval.date_sortie }}</p>
                <p>Activité pratiquée : {{ cheval.get_activite_display }}</p>
                <p>Remarques : {{ cheval.remarques }}</p>
                <p>Statut : {{ cheval.get_statut_display }}</p>
                <br />
                <p>Aptitude : {{ cheval.get_aptitude_display }}</p>
                <p>Emplacement (zone) : {{ cheval.emplacement.zone }}</p>
                <p>Emplacement (box) : {{ cheval.emplacement.box }}</p>
                <p>Date du dernier soin : {{ cheval.get_dernier_soin.date }}</p>
                <p>Date du dernier ferrage : {{ cheval.get_dernier_ferrage.date }}</p>
                <p>Date de la dernière vermifugation : {{ cheval.get_derniere_vermifugation.date }}</p>

                {% if user.is_authenticated and perms.profil.chef_ecurie %}
                <p><a class="btn btn-default" href="{% url 'cheval_update' cheval.pk %}">Modifier</a></p>
                {% endif %}
                <p><a href="{% url 'cheval_list' %}"><i class="fa fa-arrow-left"></i> Retour</a></p>
            </div>
        </div>

    </fieldset>
</div>

{% endblock %}

cheval/templates/cheval_etat.html
{% extends "base.html" %}

{% block title %}État des chevaux{% endblock %}

{% block content %}

<div class="container">
    <fieldset>

        <legend class="text-center">État des chevaux</legend>

        <table id="table" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center col-xs-2">Nom</th>
                    <th class="text-center col-xs-2">Aptitude</th>
                    <th class="text-center col-xs-2">Emplacement</th>
                    <th class="text-center col-xs-2">Dernier soin</th>
                    <th class="text-center col-xs-2">Dernier ferrage</th>
                    <th class="text-center col-xs-2">Dernière vermifugation</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th class="text-center">Nom</th>
                    <th class="text-center">Aptitude</th>
                    <th class="text-center">Emplacement</th>
                    <th class="text-center">Dernier soin</th>
                    <th class="text-center">Dernier ferrage</th>
                    <th class="text-center">Dernière vermifugation</th>
                </tr>
            </tfoot>
            <tbody>
                {% for cheval, form in chevaux.items %}
                <tr>
                    <td>{{ cheval.nom }}</td>
                    <td>
                        <form action="{% url 'aptitude_update' cheval.pk %}" method="POST">
                            {% csrf_token %}
                            {{ form.aptitude }}
                            <button class="btn btn-default" type="submit">OK</button>
                        </form>
                    </td>
                    <td>{{ cheval.emplacement }}</td>
                    <td>{{ cheval.get_dernier_soin.date }}</td>
                    <td>{{ cheval.get_dernier_ferrage.date }}</td>
                    <td>{{ cheval.get_derniere_vermifugation.date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </fieldset>
</div>

{% endblock %}

cheval/templates/cheval_list.html
{% extends "base.html" %}

{% block title %}Registre d'élevage{% endblock %}

{% block content %}

<div class="container">
    <fieldset>

        <legend class="text-center">Registre d'élevage</legend>
        {% if user.is_authenticated and perms.profil.chef_ecurie %}
        <p><a class="btn btn-primary" href="{% url 'cheval_create' %}">Nouveau</a></p>
        {% endif %}

        <table id="table" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">Nom</th>
                    <th class="text-center">Sire</th>
                    <th class="text-center">Race</th>
                    <th class="text-center">Pedigree</th>
                    <th class="text-center">Année de naissance</th>
                    <th class="text-center">Date d'entrée</th>
                    <th class="text-center">Activité</th>
                    <th class="text-center">Statut</th>
                    <th class="text-center">Aptitude</th>
                    <th class="text-center">Emplacement</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th class="text-center">Nom</th>
                    <th class="text-center">Sire</th>
                    <th class="text-center">Race</th>
                    <th class="text-center">Pedigree</th>
                    <th class="text-center">Année de naissance</th>
                    <th class="text-center">Date d'entrée</th>
                    <th class="text-center">Activité</th>
                    <th class="text-center">Statut</th>
                    <th class="text-center">Aptitude</th>
                    <th class="text-center">Emplacement</th>
                    <th class="text-center">Actions</th>
                </tr>
            </tfoot>
            <tbody>
                {% for cheval in chevaux %}
                <tr>
                    <td>{{ cheval.nom }}</td>
                    <td>{{ cheval.sire }}</td>
                    <td>{{ cheval.race }}</td>
                    <td>{{ cheval.pedigree }}</td>
                    <td>{{ cheval.annee_naissance }}</td>
                    <td>{{ cheval.date_entree }}</td>
                    <td>{{ cheval.get_activite_display }}</td>
                    <td>{{ cheval.get_statut_display }}</td>
                    <td>{{ cheval.get_aptitude_display }}</td>
                    <td>{{ cheval.emplacement }}</td>
                    <td class="text-center">
                        <a href="{% url 'cheval_detail' cheval.pk %}" title="Visualiser"><i class="fa fa-eye"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;
                        {% if user.is_authenticated and perms.profil.chef_ecurie %}
                        <a href="{% url 'cheval_update' cheval.pk %}" title="Modifier"><i class="fa fa-pencil"></i></a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </fieldset>
</div>

{% endblock %}

cheval/templates/cheval_update.html
{% extends "base.html" %}

{% block title %}Modifier la fiche de {{ cheval.nom }}{% endblock %}

{% block content %}

<div class="container">
    <fieldset>

        <legend class="text-center">Modifier la fiche de {{ cheval.nom }}</legend>

        <form action="{{ request.path }}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{form.sire.label_tag}}
                    {{form.sire}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{form.nom.label_tag}}
                    {{form.nom}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{form.race.label_tag}}
                    {{form.race}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{form.pedigree.label_tag}}
                    {{form.pedigree}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{form.annee_naissance.label_tag}}
                    {{form.annee_naissance}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{form.photo.label_tag}}
                    <img alt="Photo du cheval" src="/media/{{cheval.photo}}" class="img-responsive" />
                    {{form.photo}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{form.activite.label_tag}}
                    {{form.activite}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{form.remarques.label_tag}}
                    {{form.remarques}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{form.statut.label_tag}}
                    {{form.statut}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{form.aptitude.label_tag}}
                    {{form.aptitude}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{form.emplacement.label_tag}}
                    {{form.emplacement}}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    <p><button class="btn btn-success btn-block" type="submit">Enregistrer</button></p>
                    <p><button class="btn btn-default btn-block" type="reset">Annuler les modifications</button></p>
                    <p><a href="{% url 'cheval_list' %}"><i class="fa fa-arrow-left"></i> Retour</a></p>
                </div>
            </div>
        </form>

    </fieldset>
</div>

{% endblock %}

cheval/templates/emplacement.html
{% extends "base.html" %}

{% block title %}Liste des emplacements{% endblock %}

{% block content %}

<div class="container">
    {% if user.is_authenticated and perms.profil.chef_ecurie %}
    <fieldset>

        <legend class="text-center">Saisie d'un emplacement</legend>

        <form class="form-inline" action="{% url 'emplacement_create' %}" method="POST">
            {% csrf_token %}
            {% for field in form %}
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
            {% endfor %}
            <td><button class="btn btn-default" type="submit">Créer</button></td>
        </form>

    </fieldset>
    {% endif %}

    <fieldset>

        <legend class="text-center">Liste des emplacements</legend>

        <table id="table" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center col-xs-4">Zone</th>
                    <th class="text-center col-xs-4">Box</th>
                    {% if user.is_authenticated and perms.profil.chef_ecurie %}
                    <th class="text-center col-xs-4">Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th class="text-center">Zone</th>
                    <th class="text-center">Box</th>
                    {% if user.is_authenticated and perms.profil.chef_ecurie %}
                    <th class="text-center">Actions</th>
                    {% endif %}
                </tr>
            </tfoot>
            <tbody>
                {% for emplacement in emplacements %}
                <tr>
                    <td>{{ emplacement.zone }}</td>
                    <td>{{ emplacement.box }}</td>
                    {% if user.is_authenticated and perms.profil.chef_ecurie %}
                    <td class="text-center">
                        <a href="{% url 'emplacement_update' emplacement.pk %}" title="Modifier"><i class="fa fa-pencil"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="{% url 'emplacement_delete' emplacement.pk %}" title="Supprimer"><i class="fa fa-trash"></i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </fieldset>
</div>

{% endblock %}

cheval/templates/emplacement_delete.html
{% extends "base.html" %}

{% block title %}Supprimer l'emplacement{% endblock %}

{% block content %}

<div class="container">
    <fieldset>

        <legend class="text-center">Supprimer l'emplacement</legend>

        <p class="text-center">Voulez-vous supprimer cet emplacement ?</p>
        <form class="text-center" action="{{ request.path }}" method="POST">
            {% csrf_token %}
            <p><button class="btn btn-danger" type="submit">Supprimer</button></p>
            <p><a href="{% url 'emplacement_list' %}"><i class="fa fa-arrow-left"></i> Retour</a></p>
        </form>

    </fieldset>
</div>

{% endblock %}

cheval/templates/emplacement_update.html
{% extends "base.html" %}

{% block title %}Modifier l'emplacement {{ emplacement.box }}{% endblock %}

{% block content %}

<div class="container">
    <fieldset>

        <legend class="text-center">Modifier l'emplacement {{ emplacement.box }}</legend>

        <form action="{{ request.path }}" method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            </div>
            {% endfor %}
            <div class="row">
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    <p><button class="btn btn-success btn-block" type="submit">Enregistrer</button></p>
                    <p><button class="btn btn-default btn-block" type="reset">Annuler les modifications</button></p>
                    <p><a href="{% url 'emplacement_list' %}"><i class="fa fa-arrow-left"></i> Retour</a></p>
                </div>
            </div>
        </form>

    </fieldset>
</div>

{% endblock %}