centre_equestre/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import monte, cheval, profil, sante
from views import homepage,UserListView

urlpatterns = [
    url(r'^$', homepage),
    url(r'^users/$', UserListView.as_view(), name='users_list'),
    url(r'^monte/', include('monte.urls')),
    url(r'^cheval/', include('cheval.urls')),
    url(r'^profil/', include('profil.urls')),
    url(r'^sante/', include('sante.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monte/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^create/montoir$', CreneauMontoirCreate.as_view(), name='creneau_montoir_create'),
    url(r'^update/montoir/(?P<pk>[\w-]+)$', CreneauMontoirUpdate.as_view(), name='creneau_montoir_update'),
    url(r'^delete/montoir/(?P<pk>[\w-]+)$', CreneauMontoirDelete.as_view(), name='creneau_montoir_delete'),

    url(r'^list/montoir/previsionnel$', CreneauMontoirPrevisionnelList.as_view(), name='creneau_montoir_previsonnel_list'),
    url(r'^list/montoir/reel$', CreneauMontoirReelList.as_view(), name='creneau_montoir_reel_list'),

    url(r'^detail/montoir/previsionnel(?P<pk>[\w-]+)$', CreneauMontoirPrevisionnelDetail.as_view(), name='piquet_montoir_previsionnel'),
    # url(r'^detail/montoir/reel/(?P<pk>[\w-]+)$', CreneauMontoirReelDetail.as_view(), name='piquet_montoir_reel'),

    url(r'^create/montoir/enseignant/(?P<pk_prev>[\w-]+)$', CreneauMontoirReelCreate.as_view(), name='creneau_montoir_enseignant_create'),

    url(r'^list/piquet/reel$', PiquetReelList.as_view(), name='piquet_reel_list'),




    url(r'^piquet/update/(?P<pk>[\w-]+)/json$', PiquetMontoirJsonUpdateView.as_view(), name='update_piquet_json'),




]

cheval/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import date


STATUT_CHOICES = (
    ('1', 'Propriété'),
    ('2', 'Commodat'),
    ('3', 'Pension'),
    ('4', 'Débourrage'),
    ('5', 'Autres'),
)

ACTIVITE_CHOICES = (
    ('1', 'Monte'),
    ('2', 'Élevage'),
)

APTITUDE_CHOICES = (
    ('1', 'Apte'),
    ('2', 'Repos'),
    ('3', 'Infirmerie'),
    ('4', 'Autres'),
)


class Emplacement(models.Model):
    zone    = models.CharField(max_length = 100)
    box     = models.CharField(max_length = 100, unique = True, null = True)

    def __unicode__(self):
        return 'Zone %s - box %s' % (self.zone, self.box)

    def serialize(self):
        return {
            'zone': self.zone,
            'box': self.box,
        }


class Cheval(models.Model):
    sire            = models.IntegerField(unique = True)
    nom             = models.CharField(max_length = 100)
    race            = models.CharField(max_length = 100)
    pedigree        = models.CharField(max_length = 100)
    annee_naissance = models.IntegerField()
    photo           = models.FileField(upload_to = 'photos')
    date_entree     = models.DateField(auto_now_add = True)
    date_sortie     = models.DateField(null = True, blank = True)
    activite        = models.CharField(max_length = 1, choices = ACTIVITE_CHOICES)
    remarques       = models.TextField()
    statut          = models.CharField(max_length = 1, choices = STATUT_CHOICES)
    aptitude        = models.CharField(max_length = 1, choices = APTITUDE_CHOICES, default = '1')
    emplacement     = models.OneToOneField(Emplacement, unique = True)

    class Meta:
        verbose_name_plural = 'Chevaux'

    def get_dernier_soin(self):
        return self.soin_set.filter(acte = 1).order_by('-date').first()

    def get_dernier_vaccin(self):
        return self.soin_set.filter(acte = 2).order_by('-date').first()

    def get_dernier_ferrage(self):
        return self.soin_set.filter(acte = 3).order_by('-date').first()

    def get_derniere_vermifugation(self):
        return self.soin_set.filter(acte = 4).order_by('-date').first()

    def __unicode__(self):
        return self.nom

    def serialize(self):
        return {
            'sire': self.sire,
            'nom': self.nom,
            'race': self.race,
            'pedigree': self.pedigree,
            'annee_naissance': self.annee_naissance,
            'date_entree': self.date_entree,
            'date_sortie': self.date_sortie,
            'activite': self.activite,
            'remarques': self.remarques,
            'statut': self.statut,
            'aptitude': self.aptitude,
            'emplacement': self.emplacement,
        }


@receiver(post_save, sender = Cheval)
def add_cheval_piquet_montoir_staff(sender, instance, created, **kwargs):
    from monte.models import CreneauMontoir, PiquetMontoirStaff
    if not PiquetMontoirStaff.objects.filter(cheval = instance):
        if instance.activite == '1' and (created or (created == False and (not instance.date_sortie or instance.date_sortie > date.today()))):
            for montoir in CreneauMontoir.objects.all():
                PiquetMontoirStaff.objects.create(montoir = montoir, cheval = instance)


@receiver(post_save, sender = Cheval)
def del_cheval_piquet_montoir_staff(sender, instance, created, **kwargs):
    from monte.models import CreneauMontoir, PiquetMontoirStaff
    if created == False and (instance.date_sortie and instance.date_sortie <= date.today()) or instance.activite == '2':
        for montoir in CreneauMontoir.objects.all():
            PiquetMontoirStaff.objects.filter(cheval = instance).delete()


class Journal(models.Model):
    cheval  = models.ForeignKey(Cheval)
    date    = models.DateField()
    motif   = models.CharField(max_length = 100)
    lieu    = models.CharField(max_length = 100)

    class Meta:
        verbose_name_plural = 'Journaux'

    def __unicode__(self):
        return '%s %s' % (self.cheval.nom, self.lieu)

sante/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

from profil.models import Profil
from cheval.models import Cheval


ACTE_CHOICES = (
    ('1', 'Soin'),
    ('2', 'Vaccin'),
    ('3', 'Ferrage'),
    ('4', 'Vermifugation'),
    ('5', 'Autres'),
)


class Soin(models.Model):
    date        = models.DateField()
    cheval      = models.ForeignKey(Cheval)
    pathologie  = models.CharField(max_length = 100)
    acte        = models.CharField(max_length = 1, choices = ACTE_CHOICES)
    soigneur    = models.ForeignKey(Profil)

    def __unicode__(self):
        return '%s pour %s le %s' % (self.acte, self.cheval, self.date)

centre_equestre/views.py
from django.contrib.auth.models import User
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render,redirect

def homepage(request):
    return render(request,"homepage.html")

class UserListView(ListView):
    model = User
    template_name = 'registration/registration_form.html'
    context_object_name = 'users'
    queryset = User.objects.all().order_by('username')

centre_equestre/templates/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'DataTables/datatables.min.css' %}" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" media="screen" title="no title" charset="utf-8">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.1/css/buttons.dataTables.min.css" media="screen" title="no title" charset="utf-8">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}" media="screen" title="no title" charset="utf-8" />
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css' %}" />
    <link rel="stylesheet" href="{% static 'bower_components/datepicker/css/datepicker.css' %}" />

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <script type="text/javascript" src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'DataTables/datatables.min.js' %}"></script>

   <script type="text/javascript" src="//code.jquery.com/jquery-1.12.3.js">*</script>
   <script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js">*</script>
   <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.1/js/dataTables.buttons.min.js">*</script>
   <script type="text/javascript" src="//cdn.datatables.net/buttons/1.2.1/js/buttons.flash.min.js">*</script>
   <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js">*</script>
   <script type="text/javascript" src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js">*</script>
   <script type="text/javascript" src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js">*</script>
   <script type="text/javascript" src="//cdn.datatables.net/buttons/1.2.1/js/buttons.html5.min.js">*</script>
   <script type="text/javascript" src="//cdn.datatables.net/buttons/1.2.1/js/buttons.print.min.js">*</script>
   <script type="text/javascript" src="//cdn.datatables.net/plug-ins/1.10.11/api/sum().js">*</script>

    <script type="text/javascript" src="{% static 'bower_components/bootstrap-switch/dist/js/bootstrap-switch.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>
</head>

<body>
    {% include "header.html" %}

    {% block content %}

    {% endblock %}

</body>
</html>

centre_equestre/templates/header.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">EPLEFPA</a>
        </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          {% if user.is_authenticated and perms.profil.chef_ecurie or perms.profil.professeur %}
        <li><a href="/users">Users</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profils <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'list_profil' %}">Fiche</a></li>
                <li><a href="{% url 'list_public' %}">Publics</a></li>
            </ul>
        </li>
        {% endif %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Chevaux <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'cheval_list' %}">Registre d'élevage</a></li>
                <li><a href="{% url 'soin_list' %}">Carnet de soins</a></li>
                <li><a href="{% url 'journal_list' %}">Entrées / sorties</a></li>
                <li><a href="{% url 'emplacement_list' %}">Emplacements</a></li>
                <li><a href="{% url 'cheval_etat' %}">État des chevaux</a></li>
            </ul>
        </li>
        {% if user.is_authenticated and perms.profil.chef_ecurie or perms.profil.professeur %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Monte <span class="caret"></span></a>
            <ul class="dropdown-menu">
                {% if user.is_authenticated and perms.profil.chef_ecurie %}
                <li><a href="/monte/list/montoir/previsionnel">Montoir Prévisionnel</a></li>
                {% endif %}
                 {% if user.is_authenticated and perms.profil.chef_ecurie or perms.profil.professeur %}
                <li><a href="{% url 'piquet_reel_list' %}">Montoirs Enseignant</a></li>
                <li><a href="/monte/list/montoir/reel">Créer un montoir</a></li>
                {% endif %}
            </ul>
        </li>
        {% endif %}
        <li><a href="#">Club</a></li>
        <li><a href="#">Statistiques</a></li>
    </ul>

            {% if user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">{{user.username}}</a> </li>
                <li><a href="/accounts/logout/">Déconnexion</a></li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav navbar-right">
                <li class="connect"><a href="/accounts/login/">Se Connecter</a></li>
            </ul>
            {% endif %}

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

centre_equestre/templates/homepage.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="container-fluid homepage">
    <div class="row">
        <img src={% static 'img/image003b.jpg' %} alt="" style="width:100%" />
    </div>
    <div class="row">
        <h1>Centre Equestre de Saint Chély d'Apcher</h1>
    </div>
</div>

{% endblock %}